"""Transport-agnostic implementation of the Nuki Opener BLE protocol."""

from .advertisement import NukiAdvertisement, parse_manufacturer_data
from .client import NukiOpenerClient, NukiOpenerCredentials
from .const import (
    OPENER_SERVICE_UUID,
    PAIRING_GDIO_UUID,
    PAIRING_SERVICE_UUID,
    USDIO_UUID,
    Capability,
    ClientType,
    Command,
    CompletionStatus,
    DoorSensorState,
    ErrorCode,
    LockAction,
    LockState,
    NukiState,
    OperatingMode,
    StatusCode,
    Trigger,
)
from .device import NukiOpenerDevice, RingEvent
from .errors import (
    NukiBadPinError,
    NukiConnectionError,
    NukiCrcError,
    NukiDeviceError,
    NukiError,
    NukiNotInPairingModeError,
    NukiPairingError,
    NukiProtocolError,
    NukiResponseTimeoutError,
)
from .messages import BatteryReport, LogEntry, OpenerConfig, OpenerState

__all__ = [
    "OPENER_SERVICE_UUID",
    "PAIRING_GDIO_UUID",
    "PAIRING_SERVICE_UUID",
    "USDIO_UUID",
    "BatteryReport",
    "Capability",
    "ClientType",
    "Command",
    "CompletionStatus",
    "DoorSensorState",
    "ErrorCode",
    "LockAction",
    "LockState",
    "LogEntry",
    "NukiAdvertisement",
    "NukiBadPinError",
    "NukiConnectionError",
    "NukiCrcError",
    "NukiDeviceError",
    "NukiError",
    "NukiNotInPairingModeError",
    "NukiOpenerClient",
    "NukiOpenerCredentials",
    "NukiOpenerDevice",
    "NukiPairingError",
    "NukiProtocolError",
    "NukiResponseTimeoutError",
    "NukiState",
    "OpenerConfig",
    "OpenerState",
    "OperatingMode",
    "RingEvent",
    "StatusCode",
    "Trigger",
    "parse_manufacturer_data",
]
